name: Eskilstuna events watcher

on:
  schedule:
    # kör 05:55 UTC må–fr  (≈ 07:55 svensk sommartid, 06:55 vintertid)
    - cron: '0 7 * * 1-5'
  workflow_dispatch:      # så att du kan starta manuellt vid behov

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          pip install -r requirements.txt
          playwright install --with-deps chromium

      - name: Run scraper
        run: python play_scrape_events.py

      - name: Detect changes
        id: diff
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name  "github-actions[bot]"
          # commit om något nytt i data/
          if [[ `git status --porcelain=data/ | wc -l` -gt 0 ]]; then
            git add data/
            git commit -m "data: update $(date -u +'%Y-%m-%d')"
            echo "changed=yes" >> $GITHUB_OUTPUT
          else
            echo "changed=no" >> $GITHUB_OUTPUT
          fi

      - name: Push commit (if changed)
        if: steps.diff.outputs.changed == 'yes'
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # --- valfritt larm via Slack/webhook  -----------------
      - name: Notify Slack (only when changed)
        if: steps.diff.outputs.changed == 'yes' && env.SLACK_WEBHOOK != ''
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          NEW_COUNT=$(jq length data/events_$(date -u +'%Y-%m-%d').json)
          curl -X POST -H 'Content-type: application/json' \
               --data "{\"text\":\"$NEW_COUNT nya evenemang hittades i Eskilstuna-guiden\"}" \
               $SLACK_WEBHOOK
