name: Evenemangsguiden-koll

permissions:
  contents: write
  pages:    write
  id-token: write

on:
  schedule:
    - cron: '0 7 * * 1-5'      # 08:00 CEST vardagar
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium

      - name: Run scraper
        run: python fetch_events.py

      - name: Build HTML list
        run: |
          python - <<'PY'
          import json, datetime, pathlib, jinja2

          # 1. Beräkna datumsträngar
          now_dt    = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
          today     = datetime.date.today().isoformat()
          yesterday = (datetime.date.today() - datetime.timedelta(days=1)).isoformat()

          # 2. Läs dagens och gårdagens JSON
          data_dir = pathlib.Path("data")
          cur_file = data_dir / f"events_{today}.json"
          prev_file = data_dir / f"events_{yesterday}.json"

          events = json.load(cur_file.open(encoding="utf-8"))
          if prev_file.exists():
              prev_ids = {e["id"] for e in json.load(prev_file.open(encoding="utf-8"))}
          else:
              prev_ids = set()

          # 3. Märk nyheter
          for ev in events:
              ev["new"] = ev["id"] not in prev_ids

          # 4. Rendera HTML med både datum och tid + plats med mellanrum
          tpl = jinja2.Environment(
              loader=jinja2.FileSystemLoader("."),
              autoescape=True
          ).get_template("template.html")
          html = tpl.render(
              STAMP_DATE=today,
              STAMP_TIME=now_dt,
              COUNT=len(events),
              events=events
          )

          # 5. Spara till public/
          pub = pathlib.Path("public"); pub.mkdir(exist_ok=True)
          pub.joinpath("index.html").write_text(html, encoding="utf-8")
          PY

      - name: Commit data
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions[bot]"
          git add data/
          git commit -m "data: update $(date -u +'%Y-%m-%dT%H:%M')" || echo "nothing to commit"

      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
