name: Evenemangsguiden-koll

permissions:
  contents: write
  pages:    write
  id-token: write

on:
  schedule:
    - cron: '0 7 * * 1-5'      # 07:00 UTC vardagar
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run API scraper
        run: python fetch_events.py

      - name: Build HTML list
        run: |
          python - <<'PY'
          import json, datetime, pathlib, subprocess, jinja2
          today  = datetime.date.today()
          stamp  = today.isoformat()
          cur    = pathlib.Path(f"data/events_{stamp}.json")
          events = json.load(cur.open(encoding="utf-8"))
          count  = len(events)

          # Föregående commit av dagens fil för ”Nytt”
          try:
              prev_raw = subprocess.check_output(
                  ["git", "show", f"HEAD:{cur}"], text=True)
              prev_set = {e["id"] for e in json.loads(prev_raw)}
          except subprocess.CalledProcessError:
              prev_set = set()

          for ev in events:
              ev["new"] = ev["id"] not in prev_set

          html = jinja2.Environment(loader=jinja2.FileSystemLoader(".")) \
                 .get_template("template.html") \
                 .render(STAMP=stamp, COUNT=count, events=events)

          pub = pathlib.Path("public"); pub.mkdir(exist_ok=True)
          pub.joinpath("index.html").write_text(html, encoding="utf-8")
          PY

      - name: Commit data (always)
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name  "github-actions[bot]"
          git add data/
          git commit -m "data: update $(date -u +'%Y-%m-%dT%H:%M')" || echo "no changes"

      - uses: ad-m/github-push-action@v0.8.0
        with: { github_token: ${{ secrets.GITHUB_TOKEN }} }

      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
