name: Eskilstuna events watcher

on:
  # Kör 07:00 UTC varje vardag  (08:00 svensk vintertid, 09:00 sommartid)
  schedule:
    - cron: '0 7 * * 1-5'
  # Gör det möjligt att starta manuellt från GitHub-gränssnittet
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      # 1. Hämta repo:t
      - name: Check out repo
        uses: actions/checkout@v4

      # 2. Installera Python 3.11
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Installera Playwright + beroenden
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install chromium          # <— utan --with-deps

      # 4. Kör scraperskriptet
      - name: Run scraper
        run: python play_scrape_events.py

      # 5. Kolla om något ändrats i data/-katalogen
      - name: Detect changes
        id: diff
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name  "github-actions[bot]"
          if [[ $(git status --porcelain=data/ | wc -l) -gt 0 ]]; then
            git add data/
            git commit -m "data: update $(date -u +'%Y-%m-%d')"
            echo "changed=yes" >> $GITHUB_OUTPUT
          else
            echo "changed=no" >> $GITHUB_OUTPUT
          fi

      # 6. Skicka upp nya JSON-filer till GitHub om något förändrats
      - name: Push commit (if changed)
        if: steps.diff.outputs.changed == 'yes'
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # 7. (Valfritt) Skicka Slack-meddelande när nya evenemang hittas
      - name: Notify Slack (only when changed)
        if: steps.diff.outputs.changed == 'yes' && env.SLACK_WEBHOOK != ''
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          NEW_COUNT=$(jq length data/events_$(date -u +'%Y-%m-%d').json)
          curl -X POST -H 'Content-type: application/json' \
               --data "{\"text\":\"$NEW_COUNT nya evenemang hittades i Eskilstuna-guiden\"}" \
               $SLACK_WEBHOOK
