name: Evenemangsguiden-koll
permissions:
  contents: write
  pages:    write
  id-token: write

on:
  schedule:
    - cron: '0 7 * * 1-5'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run API scraper        # ← tillbaks till ordinarie
        run: python fetch_events.py

      # Build HTML, Commit, Deploy … (samma som tidigare)
      - name: Build HTML
        run: |
          python - <<'PY'
          import json, datetime, pathlib, subprocess, jinja2
          today = datetime.date.today().isoformat()
          cur   = pathlib.Path(f"data/events_{today}.json")
          evs   = json.load(cur.open())
          count = len(evs)
          try:
              prev_raw = subprocess.check_output(
                  ["git", "show", f"HEAD:{cur}"], text=True)
              prev_set = {e["id"] for e in json.loads(prev_raw)}
          except subprocess.CalledProcessError:
              prev_set = set()
          for e in evs:
              e["new"] = e["id"] not in prev_set
          html = jinja2.Environment(loader=jinja2.FileSystemLoader(".")) \
                 .get_template("template.html") \
                 .render(STAMP=today, COUNT=count, events=evs)
          pub = pathlib.Path("public"); pub.mkdir(exist_ok=True)
          pub.joinpath("index.html").write_text(html, encoding="utf-8")
          PY

      - name: Commit data
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name  "github-actions[bot]"
          git add data/
          git commit -m "data: update $(date -u +'%Y-%m-%dT%H:%M')" || echo "no changes"
      - uses: ad-m/github-push-action@v0.8.0
        with: { github_token: ${{ secrets.GITHUB_TOKEN }} }
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
