name: Evenemangsguiden-koll

permissions:
  contents: write
  pages: write
  id-token: write

on:
  schedule:
    # Vintertid (CET = UTC+1): 06–20 lokal -> 05–19 UTC (jan, feb, nov, dec)
    - cron: "0 5-19 * 1,2,11,12 1-5"
    # Sommartid (CEST = UTC+2): 06–20 lokal -> 04–18 UTC (mar–okt)
    - cron: "0 4-18 * 3-10 1-5"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      # Håll nya delar avstängda (kan sättas till 'true' senare)
      ENABLE_FIRST_SEEN: "false"
      PYTHONUNBUFFERED: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          # Säkerställ alla Playwright-beroenden på Ubuntu
          npx playwright install-deps chromium
          playwright install chromium

      - name: Run scraper
        run: |
          set -e
          python fetch_events.py

      - name: Sanity check (events file)
        run: |
          python sanity_check_events.py

      - name: Build HTML list (index.html)
        run: python build_html_list.py

      # --- Parkera first_seen tills vidare (påslås när skrapet är stabilt) ---
      - name: Update first_seen registry
        if: env.ENABLE_FIRST_SEEN == 'true'
        run: python update_first_seen.py

      - name: Build yesterday overview
        if: env.ENABLE_FIRST_SEEN == 'true'
        run: python build_yesterday.py
      # ----------------------------------------------------------------------

      - name: Debug: list public and data
        run: |
          echo "--- public ---"
          ls -la public || true
          echo "--- data ---"
          ls -la data || true

      - name: Commit data
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions[bot]"
          git add data/ public/
          git commit -m "data: update $(date -u +'%Y-%m-%dT%H:%M')" || echo "nothing to commit"

      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          # Om din Pages är satt till main istället för gh-pages:
          # publish_branch: main
