name: Eskilstuna events – API-inspektör

on:
  workflow_dispatch:         # startas manuellt från Actions-fliken

permissions:
  contents: read             # vi läser bara koden, pushar inget

jobs:
  inspect:
    runs-on: ubuntu-latest

    steps:
      # 1. Klona repo:t
      - uses: actions/checkout@v4

      # 2. Installera Python 3.11
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Installera beroende (requests)
      - name: Install requests
        run: pip install requests

      # 4. Kör inspektions­skriptet
      - name: Run inspector
        run: python inspect_events.py
