name: Eskilstuna events watcher

permissions:
  contents: write
  pages:    write
  id-token: write

on:
  schedule:
    - cron: '0 7 * * 1-5'     # 07:00 UTC vardagar
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps and browser
        run: |
          pip install -r requirements.txt
          playwright install chromium

      - name: Run scraper
        run: python fetch_events.py

      - name: Build HTML list
        run: |
          python - <<'PY'
          import json, datetime, pathlib, subprocess, jinja2
          stamp = datetime.date.today().isoformat()
          curr_path = pathlib.Path(f"data/events_{stamp}.json")
          events = json.load(curr_path.open(encoding="utf-8"))
          count  = len(events)

          # Föregående version av dagens fil → markera “Nytt”
          try:
              prev_raw = subprocess.check_output(
                  ["git", "show", f"HEAD:{curr_path}"], text=True
              )
              prev_set = {e["id"] for e in json.loads(prev_raw)}
          except subprocess.CalledProcessError:
              prev_set = set()

          for ev in events:
              ev["new"] = ev["id"] not in prev_set

          tpl = jinja2.Environment(loader=jinja2.FileSystemLoader("."))\
                .get_template("template.html")
          html = tpl.render(STAMP=stamp, EVENTS=events, events=events, COUNT=count)

          pub = pathlib.Path("public"); pub.mkdir(exist_ok=True)
          pub.joinpath("index.html").write_text(html, encoding="utf-8")
          PY

      - name: Commit data (if changed)
        id: diff
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name  "github-actions[bot]"
          if [[ $(git status --porcelain=data/ | wc -l) -gt 0 ]]; then
            git add data/
            git commit -m "data: update $(date -u +'%Y-%m-%dT%H:%M')"
            echo "changed=yes" >> $GITHUB_OUTPUT
          else
            echo "changed=no"  >> $GITHUB_OUTPUT
          fi

      - if: steps.diff.outputs.changed == 'yes'
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
