name: Eskilstuna events watcher

permissions:
  contents: write
  pages: write
  id-token: write

on:
  schedule:
    - cron: '0 7 * * 1-5'     # 07:00 UTC vardagar
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run inspector  # tillfälligt
        run: python inspect_events.py

      - name: Build HTML list
        run: |
          python - <<'PY'
          import json, datetime, pathlib, jinja2
          d = datetime.date.today().isoformat()
          events = json.load(open(f"data/events_{d}.json", encoding="utf-8"))
          html = jinja2.Environment(loader=jinja2.FileSystemLoader(".")) \
                 .get_template("template.html") \
                 .render(STAMP=d, events=events)
          pathlib.Path("public").mkdir(exist_ok=True)
          pathlib.Path("public/index.html").write_text(html, encoding="utf-8")
          PY

      - name: Commit data (if changed)
        id: diff
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name  "github-actions[bot]"
          if [[ $(git status --porcelain=data/ | wc -l) -gt 0 ]]; then
            git add data/
            git commit -m "data: update $(date -u +'%Y-%m-%d')"
            echo "changed=yes" >> $GITHUB_OUTPUT
          else
            echo "changed=no" >> $GITHUB_OUTPUT
          fi

      - if: steps.diff.outputs.changed == 'yes'
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
