name: Eskilstuna events watcher

permissions:
  contents: write
  pages:    write
  id-token: write

on:
  schedule:
    - cron: '0 7 * * 1-5'      # 07 UTC vardagar
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      # 1. Checka ut repo:t
      - uses: actions/checkout@v4

      # 2. Python 3.11
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Installera Python-paket + Playwright-browser
      - name: Install deps and browser
        run: |
          pip install -r requirements.txt
          playwright install chromium

      # 4. Kör scrapern
      - name: Run scraper
        run: python fetch_events.py

      # 5. Bygg HTML med “Nytt”-markering
      - name: Build HTML list
        run: |
          python - <<'PY'
          import json, datetime, pathlib, glob, jinja2
          stamp = datetime.date.today().isoformat()
          curr  = json.load(open(f"data/events_{stamp}.json", encoding="utf-8"))

          prev_set = set()
          prev_files = sorted(glob.glob("data/events_*.json"))
          if len(prev_files) > 1:
              prev_set = {e["id"] for e in json.load(open(prev_files[-2], encoding="utf-8"))}

          for ev in curr:
              ev["new"] = ev["id"] not in prev_set

          html = jinja2.Environment(loader=jinja2.FileSystemLoader("."))\
                 .get_template("template.html").render(STAMP=stamp, events=curr)

          pub = pathlib.Path("public"); pub.mkdir(exist_ok=True)
          pub.joinpath("index.html").write_text(html, encoding="utf-8")
          PY

      # 6. Commit data om något ändrats
      - name: Commit data (if changed)
        id: diff
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name  "github-actions[bot]"
          if [[ $(git status --porcelain=data/ | wc -l) -gt 0 ]]; then
            git add data/
            git commit -m "data: update $(date -u +'%Y-%m-%d')"
            echo "changed=yes" >> $GITHUB_OUTPUT
          else
            echo "changed=no"  >> $GITHUB_OUTPUT
          fi

      - if: steps.diff.outputs.changed == 'yes'
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # 7. Deploy till GitHub Pages
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
