name: Eskilstuna events watcher

on:
  schedule:
    - cron: '0 7 * * 1-5'        # 07:00 UTC = 08:00 CET / 09:00 CEST
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      # 1. Klona repo:t
      - uses: actions/checkout@v4

      # 2. Python 3.11
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Installera beroenden + Chromium
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install chromium

      # 4. Kör scraperskriptet
      - name: Run scraper
        run: python play_scrape_events.py

      # 5. Bygg HTML-sida av dagens JSON
      - name: Build HTML list
        env:
          TODAY: ${{ steps.date.outputs.today }}
        run: |
          stamp=$(date -u +'%Y-%m-%d')
          python - <<'PY'
          import json, datetime, pathlib, jinja2
          stamp = datetime.date.today().isoformat()
          data  = json.load(open(f"data/events_{stamp}.json", encoding="utf-8"))
          env   = jinja2.Environment(loader=jinja2.FileSystemLoader("."))
          tpl   = env.get_template("template.html")
          html  = tpl.render(STAMP=stamp, events=data)
          pathlib.Path("public").mkdir(exist_ok=True)
          pathlib.Path("public/index.html").write_text(html, encoding="utf-8")
          PY

      # 6. Git-commit JSON om något ändrats
      - name: Detect changes
        id: diff
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name  "github-actions[bot]"
          if [[ $(git status --porcelain=data/ | wc -l) -gt 0 ]]; then
            git add data/
            git commit -m "data: update $(date -u +'%Y-%m-%d')"
            echo "changed=yes" >> $GITHUB_OUTPUT
          else
            echo "changed=no" >> $GITHUB_OUTPUT
          fi

      # 7. Skicka commit (om ändrat)
      - if: steps.diff.outputs.changed == 'yes'
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # 8. Deploya HTML till gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
