name: Evenemangsguiden-koll

permissions:
  contents: write
  pages:    write
  id-token: write

on:
  schedule:
    - cron: '0 7 * * 1-5'     # kör 08:00 CEST vardagar
  workflow_dispatch:         # manuell trigger

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Setup Python 3.11
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Install dependencies + Chromium
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium

      # 4. Run scraper
      - name: Run scraper
        run: python fetch_events.py

      # 5. Build HTML list with daily reset of “Nytt”, spacing, and timestamp
      - name: Build HTML list
        run: |
          python - <<'PY'
          import json, datetime, pathlib, subprocess, jinja2

          # Tidsstämplar
          now       = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
          today     = datetime.date.today().isoformat()
          yesterday = (datetime.date.today() - datetime.timedelta(days=1)).isoformat()

          data_dir  = pathlib.Path("data")
          cur_file  = data_dir / f"events_{today}.json"

          # 1) Läs dagens events
          events = json.load(cur_file.open(encoding="utf-8"))

          # 2) Hämta tidigare version av dagens fil från HEAD
          try:
              prev_raw = subprocess.check_output(
                  ["git", "show", f"HEAD:data/events_{today}.json"],
                  text=True
              )
              prev_ids = {e["id"] for e in json.loads(prev_raw)}
          except subprocess.CalledProcessError:
              # Fallback till gårdagens fil om HEAD-version saknas
              prev_file = data_dir / f"events_{yesterday}.json"
              if prev_file.exists():
                  prev_ids = {e["id"] for e in json.load(prev_file.open(encoding="utf-8"))}
              else:
                  prev_ids = set()

          # 3) Markera “new” baserat på prev_ids
          for ev in events:
              ev["new"] = ev["id"] not in prev_ids

          # 4) Rendera HTML med template.html
          tpl = jinja2.Environment(
              loader=jinja2.FileSystemLoader("."),
              autoescape=True
          ).get_template("template.html")
          html = tpl.render(
              STAMP_TIME=now,
              COUNT=len(events),
              events=events
          )

          # 5) Skriv ut till public/index.html
          pub = pathlib.Path("public"); pub.mkdir(exist_ok=True)
          pub.joinpath("index.html").write_text(html, encoding="utf-8")
          PY

      # 6. Commit data files if changed
      - name: Commit data
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name  "github-actions[bot]"
          git add data/
          git commit -m "data: update $(date -u +'%Y-%m-%dT%H:%M')" || echo "nothing to commit"

      # 7. Push commits
      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # 8. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
