name: Evenemangsguiden-koll

permissions:
  contents: write
  pages:    write
  id-token: write

on:
  schedule:
    - cron: '0 7 * * 1-5'      # 08:00 CEST vardagar
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium

      - name: Run scraper
        run: python fetch_events.py

      - name: Build HTML
        run: |
          python - <<'PY'
          import json, datetime, pathlib, subprocess, jinja2
          today = datetime.date.today().isoformat()
          dataf = pathlib.Path(f"data/events_{today}.json")
          events = json.load(dataf.open(encoding="utf-8"))
          count = len(events)
          try:
              prev = subprocess.check_output(
                  ["git", "show", f"HEAD:{dataf}"], text=True
              )
              prev_ids = {e["id"] for e in json.loads(prev)}
          except subprocess.CalledProcessError:
              prev_ids = set()
          for ev in events:
              ev["new"] = ev["id"] not in prev_ids
          html = jinja2.Environment(
              loader=jinja2.FileSystemLoader(".")
            ).get_template("template.html").render(
              STAMP=today, COUNT=count, events=events
          )
          pub = pathlib.Path("public"); pub.mkdir(exist_ok=True)
          pub.joinpath("index.html").write_text(html, encoding="utf-8")
          PY

      - name: Commit data
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions[bot]"
          git add data/
          git commit -m "data: update $(date -u +'%Y-%m-%dT%H:%M')" || echo "nothing to commit"

      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
