name: Eskilstuna events – API-inspektör

# Vi behöver inga skriv-rättigheter när vi bara loggar JSON-svaret
permissions:
  contents: read

on:
  workflow_dispatch:      # körs manuellt från Actions-fliken

jobs:
  inspect:
    runs-on: ubuntu-latest

    steps:
      # 1. Klona repo:t
      - uses: actions/checkout@v4

      # 2. Python 3.11
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Installera bara requests (inspektorn kräver inget mer)
      - name: Install requests
        run: pip install requests

      # 4. Kör inspektions­skriptet
      - name: Run inspector
        run: python inspect_events.py
